### ISSUE TITLE
Investigate "Other" & Storage Costs

### ISSUE THREAD

**Issue by timalces** [openflighthpc/cloud-cost-reporter#112]
Determine what kinds of costs are included in 'other' costs and how best to separate out data storage costs.

**Comment by timalces** [comment]
For Azure:

**Other costs**
- vast majority relate to storage costs: disks, files, snapshots and images
- network costs, in particular IP addresses
- data in costs
- some previously hidden data out costs
- Any future services we add that don't come under the existing categories we look for 

**Recording storage costs**
- We can record storage costs by adding `?$expand=meterDetails` to the Azure `usageDetails` API call. These costs can then be filtered (in our application) on `"meterDetails"["meterCategory"] == "Storage"` and the total stored in a new `costLog`
- This `meterDetails` field can also be used to include/exclude the extra data out costs as needed (otherwise they are not identifiable)
- This seems better than the alternative of adding a specific storage tag to disks, snapshots, etc. and filtering costs on that tag

**Comment by timalces** [comment]
In addition to the above, for 'core' costs, we include every cost that has a core tag, other than data out costs. So if any disks, snapshots, etc. have the core tag, their costs will be included in the core cost entry. This logic will therefore need changing if we want to include these in a broader storage cost entry only.

**Comment by timalces** [comment]
For AWS:

**Other costs (based on our openflight account)**
- Mostly storage costs (EBS, S3, snapshots, etc.)
- Elastic IP
- API calls
- Data in
- Anything else we add

**Recording storage costs**
- Could make an Azure API query filtering on `USAGE_TYPE_GROUP`
- Filter for values of:` EC2: EBS - SSD(gp2), EC2: EBS - Snapshots,  EC2: EBS Optimized, S3: Storage - Standard`
- However, this means that if any extra storage types added in future we will need to add them in the code (there is no apparent overarching filter for everything storage related)
- Adding a specific storage tag would perhaps therefore be better/ more flexible for AWS projects
- As with Azure, storage costs for core infra is included in the 'core' cost entry, so this may need to change

**Comment by ColonelPanicks** [comment]
@timalces some good analysis here! Something that confuses me is that, in the case of the democluster setup in Azure, I painstakingly tagged every single resource (interfaces, disks, etc) with types & compute groups yet there are still lots of "other" costs. I'm wondering if then it's perhaps the cost reported not picking up these tags on non-instance resources?

I don't think storage costs for system disks need to be separate, certainly when it comes to storage disks it'll be more useful for showing how much shared data storage is costing.

**Comment by timalces** [comment]
> @timalces some good analysis here! Something that confuses me is that, in the case of the democluster setup in Azure, I painstakingly tagged every single resource (interfaces, disks, etc) with types & compute groups yet there are still lots of "other" costs. I'm wondering if then it's perhaps the cost reported not picking up these tags on non-instance resources?

For compute group costs, these purposefully only include the costs for running the actual instances. So disks and anything else associated with the compute instance/ group will get picked up in 'other'.

We can change our filtering to include them in the compute group instead, but the big problem then is that the compute group forecasts will always be an underestimate, as the AWS/Azure pricing we rely on is only for running the instance itself. So these other compute group costs would effectively disappear from the forecasts, unless we came up with some clever (and from my initial thoughts, complicated) way of estimating and including them in the compute groups (https://alces.slack.com/archives/C01A4K27B37/p1612173957000500?thread_ts=1611835644.027400&cid=C01A4K27B37).

For core costs on the other hand, these include costs for anything tagged as core, other than data out costs.

> I don't think storage costs for system disks need to be separate, certainly when it comes to storage disks it'll be more useful for showing how much shared data storage is costing.

So for Azure do you mean just 'Storage accounts' and for AWS just 'S3 buckets'? Or are there others we'd want too?

**Comment by ColonelPanicks** [comment]
Thanks for clarifying. 

When I say "storage disk" I'm referring to an additional virtual disk connected to the headnode that's shared with the compute nodes. The OpenFlight clusters do not have this but productions systems usually do. I think storage accounts and S3 buckets can be disregarded for now.

After revisiting the thread you linked and having a think, we should go ahead with splitting out all virtual disk costs from "Other" into their own metric, "Storage". It sounds like the mess of including them in compute groups is not worth addressing. The main goal is to reduce the size of "Other" such that it's not a significant chunk or regular running costs.

To address the note regarding the number of AWS disk types, I don't think the list would be too long to assume/gather? There are [less than 10](https://aws.amazon.com/ebs/pricing/) disk types available so if we just include those (and the S3 filter you mentioned) then that should do a decent job of covering the storage costs. (This is partially because going through and tagging every system & storage disk is not ideal from my end)

Does the above sound okay?

**Comment by timalces** [comment]
> To address the note regarding the number of AWS disk types, I don't think the list would be too long to assume/gather? There are [less than 10](https://aws.amazon.com/ebs/pricing/) disk types available so if we just include those (and the S3 filter you mentioned) then that should do a decent job of covering the storage costs. (This is partially because going through and tagging every system & storage disk is not ideal from my end)

The AWS SDK is not very flexible (and despite what their docs say, doesn't allow for searching on a partial match), so for filtering we have to specify every individual 'Usage Type group' we want in the API query, in their exact expected format. Assuming those listed in https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/ce-filtering.html are accurate it should be okay.

Sorry, I'm not sure what you mean about the S3 filter? 

> Does the above sound okay?

So just to clarify, this would be all 'EBS' costs for AWS, and all 'Disk' costs for Azure? Including those for 'core', and excluding data out costs? If so, seems alright to me.

**Comment by ColonelPanicks** [comment]
Yep, I think we should hardcore all the individual ones in to the query. You seem to have identified the ones we currently used earlier on too so we can try to add/catch the others as they get used or just gamble that we can guess the formatting correctly (or spin up some of those disks and check).

When I said "S3 Filter" I meant the entry in the list you posted before (`EC2: EBS - SSD(gp2), EC2: EBS - Snapshots, EC2: EBS Optimized, S3: Storage - Standard`).

Yes, you're correct in the clarification! Let's just lump all storage costs into one category. Will reduce "other" and give us another handy metric!

**Comment by timalces** [comment]
Resolved by #116
