### ISSUE TITLE
Support for Multiple Regions & Resource Groups

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/cloud-cost-reporter#36]
In some cases resources may be spread between regions (applies to both AWS & Azure) & resource groups (Azure-specific). I would like to be able to configure a "project" that combines the costs of multiple regions and/or resource groups into one. 

Needs some thought on implementation, initial thoughts:
- Meta-projects that combine the data from child projects
- Changes to project configuration to loop through project details to add multiple groups & regions

**Comment by timalces** [comment]
In the reports, do we want to highlight which regions the compute instances are in?
